# Generated by Django 4.2.1 on 2023-05-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cargotype'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='transport',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.transport'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cargo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.transportcompany'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.driver'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='bodyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.bodytype'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.transporttype'),
        ),
    ]
