# Generated by Django 4.2.1 on 2023-06-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('order', '0002_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='auth.group'),
        ),
    ]
