# Generated by Django 4.2.1 on 2023-05-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cargo_type_alter_driver_transport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='bodyType',
            new_name='body_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
    ]
