# Generated by Django 4.2.1 on 2023-05-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_bodytype_transport_body_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransportCompany',
            new_name='ServiceCategory',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='company',
        ),
        migrations.AddField(
            model_name='companyservice',
            name='category',
            field=models.ManyToManyField(to='order.servicecategory'),
        ),
    ]
