# Generated by Django 4.2.1 on 2023-09-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
