# Generated by Django 4.2.1 on 2023-05-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_transportcompany_servicecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['age', 'last_name', 'first_name']},
        ),
    ]
