# Generated by Django 4.2.1 on 2023-05-31 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_driver_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date', 'cost']},
        ),
    ]
