# Generated by Django 4.2.1 on 2023-06-01 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='transport',
        ),
        migrations.AddField(
            model_name='companyservice',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.companyservice'),
        ),
    ]
