# Generated by Django 4.2.1 on 2023-09-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
