# Generated by Django 4.2.1 on 2023-06-01 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_driver_transport_companyservice_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.transport'),
        ),
    ]
