# Generated by Django 4.2.1 on 2023-11-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
