# Generated by Django 4.2.1 on 2023-11-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
